### ISSUE TITLE
HW1 Clarification 

### ISSUE THREAD

**Issue by lw334** [uchicago-mobi/2016-Spring-Forum#12]
In the slides from week1, it says the parental gate should be triggered when the user tries to open about author page but in the hw requirement (on the class site) it says it should be triggered when the user accesses settings page. The slides also say that we should write settings page with objective-c but the hw requirement says we should write about author page in objective-c? Where should we use the nib file? Thanks!

**Comment by tabinks** [comment]
From the home page the user should be able to navigate to two different scenes: About the Author and Settings.
- The **Settings** scene should be written in objective-c and have a way (eg. a switch) for the user to toggle automatic read to me functionality.
- The **About the Author** scene should have the parental gate.  This is typically what you would see in a children's book because the about the author page would include links to social media, email addresses, or the App Store (to purchase more of the author's work).  This page should use an external `.nib` file (ie. do not create the view controller in Storyboard).

I will update the write-up.  Thanks for reading so closely.

**Comment by tabinks** [comment]
The write-up is updated.  I also added a couple tips inline in the write-up.
