### ISSUE TITLE
UICollectionView in a UIViewController

### ISSUE THREAD

**Issue by hbennett766** [uchicago-mobi/2016-Spring-Forum#127]
I'm trying (and failing) to put a UICollectionView in a UIViewController. I have all the required delegate/datasource methods set up. Right now I'm getting "fatal error: unexpectedly found nil while unwrapping an Optional value" at the line with ****. selectionCV is coming up as nil, and I'm not sure why.

Here's the relevant code:

class CreateViewController: UIViewController, UICollectionViewDelegate, UICollectionViewDataSource {

// hooked up to storyboard
@IBOutlet weak var selectionCV: UICollectionView!

override func viewDidLoad() {
        super.viewDidLoad()

```
    let layout = UICollectionViewFlowLayout()
    let space: CGFloat = 0
    layout.itemSize = CGSizeMake(50, 50)
    layout.minimumInteritemSpacing = space
    layout.minimumLineSpacing = space

    selectionCV = UICollectionView(frame: self.view.bounds, collectionViewLayout: layout)
```

  ****selectionCV.registerClass(UICollectionViewCell.self, forCellWithReuseIdentifier: "selectionCell")
        selectionCV.dataSource = self
        selectionCV.delegate = self
}
}

Any ideas? Thanks!

**Comment by susanstevens** [comment]
Since you created your collection view in storyboard, you don't need to initialize one programmatically, which is what you're doing right above the line that crashes.  That's essentially disconnecting your IBOutlet, which is why it's nil.

Also, the layout code can be taken care of in storyboard as well (unless there's a particular reason you want to do it programmatically).  And if your collection view is taking up the whole screen, you might find it easier to use a 'UICollectionViewController'.

**Comment by hbennett766** [comment]
I actually have 5 collection views. It's gonna be a party. But thank you! I'll try this out and see how it goes.
