### ISSUE TITLE
Custom Error Type for Gesture Based Parental Gate

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Spring-Forum#20]
My parental gate has 3 different shapes, and the parent has to touch the circle with 3 fingers. How do I incorporate a custom error type and validation on the touches since I'm using gesture recognizers instead of having the parent type something?

If I didn't need to incorporate the custom error type and validation method using the do-try-throw method, I would only add a gesture recognizer to the circle and then the logic for testing for success would go in the method associated with that gesture recognizer. 

Since we're supposed to use custom error types, I've also added gesture recognizers to the triangle and square, and I made a custom error type with a Triangle case, Square case, and WrongNumberOfTouches case.

I don't know how to actually validate the touch though - t's not like the example from class where you have a simple validate function. Should I make my gesture recognizers instance variables so they can be called outside of my function that simply adds the gestures to the shapes and then pass those recognizers into a function that checks which shape was touched and how many touches there were?

**Edit:** I wrote a function validateTouches - do I actually need to call it to check that the parental gate was successfully unlocked or is it enough that I wrote it? In the example you gave us, you call validateUser and show an alert to communicate to the user, but I think that showing an alert and explaining what went wrong defeats the purpose of the parental gate...

**Comment by susanstevens** [comment]
You definitely need to call the validation function so that we can see that you're handling the errors correctly.  You don't need to show an alert to the user, though.  It's up to you to decide what happens onscreen if the user fails to unlock the parental gate.  One option is to just dismiss the parental gate and take the user back to the home screen.

**Comment by aaizuss** [comment]
@susanstevens I'm trying to implement what we talked about at office hours but I'm stuck. So far:

I declared a protocol in my ParentalGateViewController like this: 
![screen shot 2016-04-10 at 9 24 59 pm](https://cloud.githubusercontent.com/assets/11274851/14415267/b3f979e4-ff62-11e5-9bc7-03a1c562c08d.png)

I have a gesture recognizer for each shape on the screen and a function that determines which shape was touched. Depending on which shape was touched, I set boolean values (tappedTriangle, tappedSquare, and pressedCircle):
![screen shot 2016-04-10 at 9 26 55 pm](https://cloud.githubusercontent.com/assets/11274851/14415293/fb3b7d8e-ff62-11e5-8ab7-c52d542e0217.png)

And I have a function validateTouches:
![screen shot 2016-04-10 at 9 27 39 pm](https://cloud.githubusercontent.com/assets/11274851/14415302/1262cf44-ff63-11e5-8033-a01c36b6f58f.png)

And in my HomeViewController, I don't actually know how to implement `unlockGate`
I know I want to test for success and show the author page or dismiss the parental gate view controller, but I'm trying to follow the do try pattern like from the slides: 
![screen shot 2016-04-10 at 9 35 35 pm](https://cloud.githubusercontent.com/assets/11274851/14415384/2ca6625c-ff64-11e5-9b81-e360f8148d6d.png)

but I can't access my TouchValidationError enum from the HomeViewController class (even though I have a reference to ParentalGateViewController called gate and use `gate.TouchValidationError.Square`)

It would be simple if I didn't have the validateTouches function because I think handleShapeTouch does what I need - I could just test that pressedCircle is true and then present the author page that way. But then I'm not really using the custom error stuff. Do you have any suggestions?

**Comment by tabinks** [comment]
I'm sure I missed a lot of the discuss between you and @susanstevens, so I may not be following everything.  Here's what I can suggest:

> I can't access my TouchValidationError enum from the HomeViewController class (even though I have > a reference to ParentalGateViewController called gate and use gate.TouchValidationError.Square)

Make sure the `enum` declaration outside of your `HomeViewController` class.  You will be able to access it from anywhere then.  Enums can be scoped inside of classes, but then they are only available inside the scope of that class.

> It would be simple if I didn't have the validateTouches function because I think handleShapeTouch does what I need - I could just test that pressedCircle is true and then present the author page that way. 

From your implementation this sounds true...it sounds like you actually validating twice.  The point of this is to get practice with custom ErrorHandling.  It may not be efficient in your case, but its good practice.

**Comment by aaizuss** [comment]
I'm also confused by where I actually call my unlockGate function. I implemented it in HomeViewController (and I'm not sure what it should be returning - currently I have it returning a UIViewController), and I think I should be calling it in my ParentalGateViewController but within this class I don't know where...  (honestly it doesn't seem possible to make this work using this validation pattern)

At this point I'm tempted to change my parental gate so it asks for user input that I can easily validate

**Comment by susanstevens** [comment]
Here's the pattern we talked about yesterday.  Each shape has a gesture recognizer, and they're all connected to the same IBAction in `ParentalGateViewController`.  The IBAction function is analogous to the `tapSubmitButton` function in the example.  It contains a do-try-catch block that calls your validation method, which is analogous to `validateUser` in the example.

So the IBAction is responsible for catching any errors thrown by the validation method, not the other way around (which is what it looks like you have in the code above).

In this pattern, `HomeViewController` doesn't need to know what errors were thrown by the validation method in `ParentalGateViewController`.  It just needs to know when to dismiss the parental gate and whether or not to present the "About the author" page.  One way for the parental gate to communicate this information back to the `HomeViewController` is with a delegate.  The `HomeViewController` would need to conform to the `ParentalGateDelegate` protocol (i.e., implement the `unlockGate` method).  When the parental gate has validated the user's gesture input, it calls `delegate?.unlockGate(success: true)` or `delegate?.unlockGate(success: false)`.

If you're still stuck, it might be helpful to think through how this would work if your parental gate needed to validate a string entered into a text field, which would follow the example from class more closely.  Then think about what you would or wouldn't need to change if your input was a gesture instead of a string.

**Comment by aaizuss** [comment]
@susanstevens okay this is really helpful! The issue now is that if the IBAction method is responsible for catching errors thrown by the validation method, then I don't know how to write the validation method. The only way to know which shape was touched is by checking in the IBAction method, and that's what the validate method is checking. The only way I can think of writing the validation method with the guard throw format is to guard which shapes were touched, and I don't know how I can do that without using results from the IBAction method, but you're saying that the IBAction method should be calling validateTouches. (maybe my validateTouches function should have a gesture recognizer parameter...?)

update: I wrote this which is really redundant but the only way I could think of following the pattern.
![screen shot 2016-04-11 at 12 51 26 pm](https://cloud.githubusercontent.com/assets/11274851/14436857/2984749e-ffe4-11e5-9a09-3b0fb30cd749.png)
And I guess where the print statements are I'll call `delegate?.unlockGate(success: true)` or `delegate?.unlockGate(success: false)`

**Comment by aaizuss** [comment]
It's not actually working though. It's detecting the touches properly (the print statements show that) but I must have implemented unlockGate incorrectly because the gate isn't being dismissed/the author page isn't being shown. Right now this is my implementation in HomeViewController:
![screen shot 2016-04-11 at 1 04 01 pm](https://cloud.githubusercontent.com/assets/11274851/14437230/e333b07a-ffe5-11e5-9099-142fc4ba7e3d.png)

**Comment by tabinks** [comment]
Amanda: we can discuss this tonight. I can't really follow what's going on in that thread.  Just make sure everything else is ready to show off to the class tonight :-)
