### ISSUE TITLE
Testing on a Device

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Spring-Forum#54]
I tried testing the app on my iPhone, but I get the code sign error:

"No matching provisioning profiles found: None of the valid provisioning profiles allowed the specified entitlements: com.apple.security.application-groups."

I think I need to register an app ID according to [this](https://developer.apple.com/library/ios/documentation/IDEs/Conceptual/AppDistributionGuide/MaintainingProfiles/MaintainingProfiles.html)

But I can't do that unless I have a paid developer account. I just purchased a membership but it apparently might take to 48 hours to process. My account doesn't really give me any options right now. I just want to make sure there isn't anything I can do to be able to test my app before the membership goes through.

**Comment by susanstevens** [comment]
You don't need a paid developer account to run your app on a device anymore (a paid account used to be required, but Apple changed that last year).  You do need to add a developer account on Xcode, but it can be a paid or free account.

To add your developer account, go to Xcode > Preferences > Accounts.  Then select your project file (the file at the very top of the project navigator on the left).  Select your app under Targets, then click on General.  Click on "Fix Issue" under the Identity section at the top and Xcode will walk you through the steps to create a provisioning profile.  You might want to try all of this on an app that doesn't use app groups first, just to make sure you have everything working.

Since we're using app groups for this project, you also need to make sure that that capability is added to all of your targets.  Select the first target, then click Capabilities (next to General), scroll down to App Groups and turn it on.  Click the plus button to add a new app group.  (Make sure you choose a unique name for it.)  Repeat this for all of your targets (i.e., the app itself, plus each of your extensions).

I'm not totally sure what will happen since your paid developer account hasn't been processed yet, but I would assume all of this should work anyway since a paid account isn't required for any of this.  (There are certain things you _can't_ do without a paid account, like use iCloud or submit an app to the app store, but I don't think you need a paid account for app extensions.  I suppose you could always create a free developer account with a different email address to use while you're waiting for the paid account to be processed.)

**Comment by aaizuss** [comment]
@susanstevens Okay, I'll create a provisioning profile. Another issue I've been having is that I do have app groups turned on for every target, but it doesn't add the entitlement to my apple id. It says communication with apple failed, and clicking "Fix Issue" doesn't resolve it. 
![screen shot 2016-04-24 at 3 51 07 pm](https://cloud.githubusercontent.com/assets/11274851/14770320/71763198-0a34-11e6-8d4f-f8caeffaecbf.png)

**Comment by susanstevens** [comment]
You need to have provisioning profile set up before you can add the app group.  Try getting that working first.

**Comment by aaizuss** [comment]
@susanstevens I set up a provisioning profile and I'm still having the issue.

**Comment by susanstevens** [comment]
Even if you add a new app group, rather than just hitting Fix Issue?  We might need to look at it together during office hours or after class tomorrow.

**Comment by aaizuss** [comment]
Yes, even when I do that. I guess I'll show you tomorrow

**Comment by tabinks** [comment]
I'm sure you tried it, but shut down Xcode, restart your computer and then try again.  Sometimes that words when dealing with provisioning profiles.

**Comment by susanstevens** [comment]
@aaizuss Looks like I was wrong about being able to create app groups without a paid developer account: https://developer.apple.com/programs/whats-included/.  App groups are listed in "Advanced App Capabilities."
