### ISSUE TITLE
Topic Soup

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2016-Spring-Forum#8]
Please add any topics you are interested in learning about this quarter.

**Comment by susanstevens** [comment]
@msylvester's comment from the winter forum: 

"I heard you ask us in class last Monday what would be cool topics to discuss (instead of Sprite kit or in addition). Two topics that interest me:
Cocoa pods
Cloud services (iCloud, Google app engine, Parse..wait)
Not to say I am not interested in Sprite kit because I think it would be cool too."

I've also heard some interest in learning autolayout, which I imagine is on the docket for later this quarter.  (I ❤️ UIStackView.)
